using System.Windows.Forms.VisualStyles;

namespace CarsApp.UI
{
    partial class CarServiceList
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">True if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            this.CarServiceCollectionBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.CarServiceCollectionGrid = new LGBS.MVPFramework.Controls.LGBSGridView();
            ((System.ComponentModel.ISupportInitialize)(this.CarServiceCollectionBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CarServiceCollectionGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CarServiceCollectionGrid.MasterTemplate)).BeginInit();
            this.SuspendLayout();
            // 
            // CarServiceCollectionBindingSource
            // 
            this.CarServiceCollectionBindingSource.DataSource = typeof(CarsApp.Data.CarServicesView);
            // 
            // CarServiceCollectionGrid
            // 
            this.CarServiceCollectionGrid.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.CarServiceCollectionGrid.BackColor = System.Drawing.SystemColors.Control;
            this.CarServiceCollectionGrid.Cursor = System.Windows.Forms.Cursors.Default;
            this.CarServiceCollectionGrid.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.CarServiceCollectionGrid.ForeColor = System.Drawing.SystemColors.ControlText;
            this.CarServiceCollectionGrid.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.CarServiceCollectionGrid.Location = new System.Drawing.Point(1, 1);
            // 
            // CarServiceCollectionGrid
            // 
            this.CarServiceCollectionGrid.MasterTemplate.AllowAddNewRow = false;
            this.CarServiceCollectionGrid.MasterTemplate.AllowColumnReorder = false;
            this.CarServiceCollectionGrid.MasterTemplate.AllowDeleteRow = false;
            this.CarServiceCollectionGrid.MasterTemplate.AllowEditRow = false;
            this.CarServiceCollectionGrid.MasterTemplate.AllowRowResize = false;
            this.CarServiceCollectionGrid.MasterTemplate.AutoGenerateColumns = false;
            this.CarServiceCollectionGrid.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "Name";
            gridViewTextBoxColumn1.FormatString = "";
            gridViewTextBoxColumn1.HeaderText = "Nazwa";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "Name";
            gridViewTextBoxColumn1.Width = 474;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "NumberOfServicedCars";
            gridViewDecimalColumn1.FormatString = "";
            gridViewDecimalColumn1.HeaderText = "Ilość serwisowanych samochodów";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "NumberOfServicedCars";
            gridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewDecimalColumn1.Width = 476;
            this.CarServiceCollectionGrid.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewTextBoxColumn1,
            gridViewDecimalColumn1});
            this.CarServiceCollectionGrid.MasterTemplate.DataSource = this.CarServiceCollectionBindingSource;
            this.CarServiceCollectionGrid.MasterTemplate.EnableAlternatingRowColor = true;
            this.CarServiceCollectionGrid.MasterTemplate.EnableFiltering = true;
            this.CarServiceCollectionGrid.MasterTemplate.EnableGrouping = false;
            this.CarServiceCollectionGrid.MasterTemplate.ShowRowHeaderColumn = false;
            this.CarServiceCollectionGrid.Name = "CarServiceCollectionGrid";
            this.CarServiceCollectionGrid.ReadOnly = true;
            this.CarServiceCollectionGrid.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.CarServiceCollectionGrid.ShowGroupPanel = false;
            this.CarServiceCollectionGrid.ShowNoDataText = false;
            this.CarServiceCollectionGrid.Size = new System.Drawing.Size(950, 510);
            this.CarServiceCollectionGrid.TabIndex = 1;
            // 
            // CarServiceList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(951, 537);
            this.Controls.Add(this.CarServiceCollectionGrid);
            this.Name = "CarServiceList";
            this.Text = "Serwisy";
            ((System.ComponentModel.ISupportInitialize)(this.CarServiceCollectionBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CarServiceCollectionGrid.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CarServiceCollectionGrid)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.BindingSource CarServiceCollectionBindingSource;
        private LGBS.MVPFramework.Controls.LGBSGridView CarServiceCollectionGrid;
    }
}
