//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarProducts
    {
        public CarProducts()
        {
            this.HandledCarProducts = new HashSet<HandledCarProducts>();
            this.CarFeatures = new HashSet<CarFeatures>();
        }
    
        public long Id { get; set; }
        public short Year { get; set; }
        public string VIN { get; set; }
        public long CarModelId { get; set; }
        public long FactoryId { get; set; }
    
        public virtual CarModels CarModels { get; set; }
        public virtual Factories Factories { get; set; }
        public virtual ICollection<HandledCarProducts> HandledCarProducts { get; set; }
        public virtual ICollection<CarFeatures> CarFeatures { get; set; }
    }
}
