//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarServices
    {
        public CarServices()
        {
            this.HandledCarProducts = new HashSet<HandledCarProducts>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public long CityId { get; set; }
        public string PostCode { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual ICollection<HandledCarProducts> HandledCarProducts { get; set; }
    }
}
