//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsDbEntities : DbContext
    {
        public CarsDbEntities()
            : base("name=CarsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CarFeatures> CarFeatures { get; set; }
        public DbSet<CarModels> CarModels { get; set; }
        public DbSet<CarProducts> CarProducts { get; set; }
        public DbSet<CarServices> CarServices { get; set; }
        public DbSet<Cities> Cities { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<Factories> Factories { get; set; }
        public DbSet<HandledCarProducts> HandledCarProducts { get; set; }
        public DbSet<Manufactures> Manufactures { get; set; }
    }
}
