//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandledCarProducts
    {
        public long CarServiceId { get; set; }
        public long CarProductId { get; set; }
        public System.DateTime HandleDate { get; set; }
        public bool IsFixed { get; set; }
        public System.DateTime FixDate { get; set; }
    
        public virtual CarProducts CarProducts { get; set; }
        public virtual CarServices CarServices { get; set; }
    }
}
