//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsApp.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarsApp.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowego kraju.
        /// </summary>
        internal static string CaptionAddCountry {
            get {
                return ResourceManager.GetString("CaptionAddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samochody.
        /// </summary>
        internal static string CaptionCarProductList {
            get {
                return ResourceManager.GetString("CaptionCarProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowego miasta.
        /// </summary>
        internal static string CaptionCityAdd {
            get {
                return ResourceManager.GetString("CaptionCityAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasta kraju:.
        /// </summary>
        internal static string CaptionCityCountryMode {
            get {
                return ResourceManager.GetString("CaptionCityCountryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane szczegółowe miasta.
        /// </summary>
        internal static string CaptionCityDetails {
            get {
                return ResourceManager.GetString("CaptionCityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja miasta.
        /// </summary>
        internal static string CaptionCityEdit {
            get {
                return ResourceManager.GetString("CaptionCityEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasta.
        /// </summary>
        internal static string CaptionCityList {
            get {
                return ResourceManager.GetString("CaptionCityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasta kraju: .
        /// </summary>
        internal static string CaptionCityOneCountryList {
            get {
                return ResourceManager.GetString("CaptionCityOneCountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane szczegółowe kraju.
        /// </summary>
        internal static string CaptionCountryDetails {
            get {
                return ResourceManager.GetString("CaptionCountryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraje.
        /// </summary>
        internal static string CaptionCountryList {
            get {
                return ResourceManager.GetString("CaptionCountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja kraju.
        /// </summary>
        internal static string CaptionEditCountry {
            get {
                return ResourceManager.GetString("CaptionEditCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabryki.
        /// </summary>
        internal static string CaptionFactoryList {
            get {
                return ResourceManager.GetString("CaptionFactoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgAdd {
            get {
                object obj = ResourceManager.GetObject("ImgAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCancel {
            get {
                object obj = ResourceManager.GetObject("ImgCancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgClear {
            get {
                object obj = ResourceManager.GetObject("ImgClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgClear16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgClear16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCompany {
            get {
                object obj = ResourceManager.GetObject("ImgCompany", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCopy15x15 {
            get {
                object obj = ResourceManager.GetObject("ImgCopy15x15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCut15x15 {
            get {
                object obj = ResourceManager.GetObject("ImgCut15x15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgDelete {
            get {
                object obj = ResourceManager.GetObject("ImgDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgDetails {
            get {
                object obj = ResourceManager.GetObject("ImgDetails", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgEdit {
            get {
                object obj = ResourceManager.GetObject("ImgEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgFormat {
            get {
                object obj = ResourceManager.GetObject("ImgFormat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgPaste {
            get {
                object obj = ResourceManager.GetObject("ImgPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgSave {
            get {
                object obj = ResourceManager.GetObject("ImgSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgSearch {
            get {
                object obj = ResourceManager.GetObject("ImgSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgSearch16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgSearch16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgViewText {
            get {
                object obj = ResourceManager.GetObject("ImgViewText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
